window:
  width: 500
  height: 500
  left_horizontal_buffer: 25
  right_horizontal_buffer: 25
  top_vertical_buffer: 70
  bottom_vertical_buffer: 0

player:
  bullet:
    speed: 25
    radius: 5

enemy:
  standard_point_value: 10
  shooter_point_value: 20
  shooting_frequency: 0.2
  speed: 5
  radius: 10
  bullet:
    speed: 10
    radius: 3
