window:
  width: 500
  height: 500
  left_horizontal_buffer: 25
  right_horizontal_buffer: 25
  top_vertical_buffer: 70
  bottom_vertical_buffer: 0

bullet:
  speed: 25
  radius: 5

enemy:
  point_value: 10
