window:
  width: 500
  height: 500
  left_buffer: 25
  right_buffer: 25
  top_buffer: 70
  bottom_buffer: 10

player:
  bullet:
    speed: 20
    radius: 3
    recoil: 0.1

enemy:
  standard_point_value: 10
  shooter_point_value: 20
  shooting_frequency: 0.2
  speed: 5
  radius: 10
  bullet:
    speed: 10
    radius: 3
    recoil: 1.5

scorebox:
  x: 400
  y: 5
